Blog app - integration specs for views and fix n+1 problems
shegy28/rails-blog pull request #8
Opened 2023-04-10 17:51 UTC by shegy28

### Add  integration specs for views and fix n+1 problems

**In this branch we implemented the following:**

- Made sure that the N+1 problem is solved when fetching all posts and their comments for a user.
-  Used Capybara to write some integration tests for the:
-  User Index page
-  User Show page
-  User Post Index page
-  Post Show page

Screenshots below:
![n+1 issue 1](https://user-images.githubusercontent.com/111022896/230960991-ee80ddaf-5970-4bea-88f2-f9ce8949662e.png)

![Screenshot (5)](https://user-images.githubusercontent.com/111022896/230961051-36639012-4a2d-4d2f-a943-ca1e3b20bf3f.png)

2023-04-10 18:48 UTC, rloterh requested changes
Hi Chimezie, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project, but you are almost there! 🏁 🚦    🏃 🌴  🏫 🌳 🏘️ 

## Highlights 👍  
- N + 1 problem addressed!

## Required Changes ♻️
_Kindly check the inline comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

**You can also consider:**
- Kindly include appropriate instructions in your ReadMe on how to run the _Rspec_ specs for this app, under the _Getting Started_ section. Implementing the above change(s) will make your ReadMe/ repository stand out even better! 😉


Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-10 18:48 UTC, rloterh commented on spec/views/users_index_spec.rb
> +  describe 'users#index' do
- [ ] Kindly also include test for the following:
  * When I click on a user, I am redirected to that user's show page.

2023-04-10 18:48 UTC, rloterh commented on spec/views/users_show_spec.rb
> +
- [ ] Similarly, please ensure provide the following test cases for the _User show_ view:
   * I can see the user's profile picture.
   * I can see the user's username.
   * I can see the number of posts the user has written.
   * I can see the user's bio.
   * I can see the user's first 3 posts.
   * I can see a button that lets me view all of a user's posts.
   * When I click a user's post, it redirects me to that post's show page.
   * When I click to see all posts, it redirects me to the user's post's index page.

2023-04-10 18:48 UTC, rloterh commented on spec/views/posts_index_spec.rb
> +
- [ ] Again, let's ensure to provide the following test scenarios for the _post index view_:
   * I can see a section for pagination if there are more posts than fit on the view.
   * When I click on a post, it redirects me to that post's show page.

2023-04-10 18:48 UTC, rloterh commented on spec/views/posts_show_spec.rb
> +
- [ ] Lastly, please provide the below test scenario for _post show_ view:
   * I can see the comment each commenter left.

2023-04-10 18:48 UTC, rloterh commented on spec/views/posts_show_spec.rb
> +      expect(page).to have_content(@post1.title)
- [ ] One of the integration specs for _post show_ view is failing. Kindly ensure that all test cases are passing!

**Failing test case:**
![image](https://user-images.githubusercontent.com/12745474/230970465-a38e7771-561c-489b-a328-aa9dff49190b.png)

2023-04-11 01:00 UTC, Reem-lab approved these changes
# Hi Team,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥💯💯
<img src="https://media2.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>

## Highlights 🔥🔥🔥🔥
- Followed Gitflow ✅
- Great working on the functionality 🔥🔥
- ALl the requested changes are applied well ✅🤩




## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 15:50 UTC, merged